### ISSUE TITLE
No syntax-variables.less

### ISSUE THREAD

**Issue by olmokramer** [ramonmcros/skeletor-syntax#1]
Other packages might depend on syntax themes providing a `syntax-variables.less` file, so they can use colors defined by the syntax to keep in style with the syntax theme. For example, [my UI theme does this](https://github.com/olmokramer/atom-dark-flat-ui/blob/master/stylesheets/tabs.less#L2) to give the active tab the same `background-color` as the editor.
Take a look at [atom-one-dark-syntax](https://github.com/atom/one-dark-syntax) for the variables that <em>should</em> be defined in `syntax-variables.less`.

Otherwise I love the theme :)

**Comment by ramonmcros** [comment]
I wasn't aware of that. I'll try to fix it.

Thanks :)

**Comment by olmokramer** [comment]
Great! I'll be eagerly waiting for the update :)

**Comment by olmokramer** [comment]
By the way, the `syntax-variables.less` should be inside the `styles/` directory in your package's root, so

```
skeletor-syntax/
├─ styles/
│  └─ syntax-variables.less
│
├─ index.less
└─ package.json
```

**Comment by ramonmcros** [comment]
Done! Let me know if it's ok or there is something to improve.

**Comment by olmokramer** [comment]
Looks good to me :) Thanks!
