### ISSUE TITLE
How can I remove the line on the editor?

### ISSUE THREAD

**Issue by xandor-io** [ramonmcros/skeletor-syntax#3]

**Comment by ramonmcros** [comment]
Hi xandorxicay,

What line?

**Comment by xandor-io** [comment]
![screen shot 2015-05-13 at 12 07 42 pm](https://cloud.githubusercontent.com/assets/4420997/7615032/b276dbb2-f968-11e4-8e03-ba0e581fa8d2.png)

**Comment by xandor-io** [comment]
I guess this is not a bug but It be nice if you could take it out :+1:

**Comment by ramonmcros** [comment]
It isn't an issue related to the theme, you have to disable the `wrap-guide` package. :wink:

**Comment by xandor-io** [comment]
Thanks I love this theme btw! cheers!
