### ISSUE TITLE
No longer searchable in Atom

### ISSUE THREAD

**Issue by adam820** [ramonmcros/skeletor-syntax#5]
Hello! I love this theme; however, it's no longer searchable in Atom (unless my eyes are just really bad). Searching 'skeletor-syntax' under the Packages installer doesn't turn up any results. Downloading the latest release and extracting into the appropriate directory still works, however.

**Comment by ramonmcros** [comment]
Hello! Are you sure you searched it under the Themes tab? It works for me.

<img width="753" alt="captura de pantalla 2017-06-23 a las 19 30 54" src="https://user-images.githubusercontent.com/9437014/27493627-aaf32434-584a-11e7-824f-a497f3807759.png">

**Comment by adam820** [comment]
You are correct; I was looking under packages. Whoops!

Closing.
